//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_04
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeathPeople
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronymic { get; set; }
        public int Gender { get; set; }
        public System.DateTime Birthday { get; set; }
        public int PlaceOfBirthID { get; set; }
        public System.DateTime Deathday { get; set; }
        public int PlaceOfDeathId { get; set; }
        public int CauseOfDeathId { get; set; }
    
        public virtual CauseOfDeath CauseOfDeath { get; set; }
        public virtual CountryInfo CountryInfo { get; set; }
        public virtual CountryInfo CountryInfo1 { get; set; }
        public virtual GenderType GenderType { get; set; }
    }
}
