//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_04
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewbornPeople
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronymic { get; set; }
        public int GenderId { get; set; }
        public System.DateTime BirthdayDate { get; set; }
        public int PlaceOfBirthId { get; set; }
        public string MotherInfo { get; set; }
        public string FatherInfo { get; set; }
    
        public virtual CountryInfo CountryInfo { get; set; }
        public virtual GenderType GenderType { get; set; }
    }
}
